### ISSUE TITLE
Game Not Launching with the Mod Installed

### ISSUE THREAD

**Issue by Atou-Mahogany** [PippleCultist/HoloCureCharacterCreatorMod#1]
I followed everything in the installation step by step, but when I try to launch the game using Aurie it doesn't even start up, and when I try to use the Executable directly, I only get a small black info screen (which I have provided a screen cap of) that quickly goes away.

![error file](https://github.com/user-attachments/assets/11779d2f-1345-43ec-bd89-cbdf3fb4fde1)

When I uninstall the mod the game starts up like normal.

I guess the only thing of note, is that I do not use the Steam version of the game, I use the (latest) itch.io version to play the game normally.

**Comment by PippleCultist** [comment]
Another person has reported that the mod doesn't work with the itch version of the game, and they managed to get it working after using the steam version. I would suggest using the steam version until I figure out what's causing the issue.

**Comment by Atou-Mahogany** [comment]
I shall respectfully decline your suggestion, as I posses a personal bias against Steam, and will patiently wait for the issue to be resolved.

**Comment by PippleCultist** [comment]
This issue is now fixed in v1.0.1

**Comment by Atou-Mahogany** [comment]
It is still not working and giving me the same error as before. Testing what I could, the game will not even open with "CallbackManagerMod.dll" installed, but opens if just the other two files are installed. However, they do not change anything in the game.

**Comment by PippleCultist** [comment]
That's odd since I tested it with the itch version, and it works fine. Make sure that you are only using the mods provided with the v1.0.1 release. Also, can you check the `Log` folder that is located in the same directory as `HoloCure.exe`?

**Comment by Atou-Mahogany** [comment]
I checked the Log folder and it is empty. I re-checked after trying to run the game with the mods installed, and again after running the game with the mods not installed, but the folder was empty every time.

Also, just to be extra sure, I re-downloaded the files for v1.01; again again.
Still not working.

So next I tried downloading a fresh copy of the game from itch to my desktop, and then tried applying the mods to that copy. For some reason, the mod files are not even showing up in my desktop copy of the game, despite Aurie showing that everything has been installed correctly.

I've been thinking, is it possible that Aurie/the mods are not compatible with my OS?
I am running Windows 7 Pro.

**Comment by PippleCultist** [comment]
I have updated `CallbackManagerMod` to not use a function that people have reported to be crashing on Windows 7. I can't test it since I don't have a Windows 7 computer, so please let me know if it stops crashing.

**Comment by Atou-Mahogany** [comment]
Okay! The game is now opening with the Mod installed and has stopped crashing.

However...

There are now some other issues:

1. The example character that we can use as a reference for creating characters is not loading. They appear to not be in the game at all?

2. For that matter, no assets seems to be loading/loaded for the character creator to be able to make a character. I tried to piece one together as a test, but even though the GUI was visible and clickable, no actual options were appearing to select from.

3. Only the mouse is able to select an option in the Mod GUI. Trying to use the keyboard won't let you select an option, it can only move the option highlighter and exit back from a menu. Unless you are in the Create Character menu, at that point only the arrow keys works, and the mouse has to be used to select/enter/exit menus.

4. Even after clicking around and causing the game to crash a few times (not unexpected as I was trying to load stuff from "empty" slots), the Logs folder is still empty.

**Comment by PippleCultist** [comment]
I updated the callback manager mod again to hopefully not have any more issues with generating the log this time. It sounds like it's not able to find the character directory. Are you sure you put the example character folder in the `CharacterCreatorMod` folder?

**Comment by Atou-Mahogany** [comment]
It is now generating logs.

I have very little experience with using github and find its layout un-intuitive most of the time, needing to rely on direct links/precise wording to find stuff mostly. Are you saying there is a folder I need to download separately to get the example character / character creator working? If so, how?

**Comment by PippleCultist** [comment]
![Example](https://github.com/user-attachments/assets/0ae1e5bf-bc0e-4020-bf39-25bcf87ece83)

You should copy the `char_test` folder and put it in the `CharacterCreatorMod` folder in order for the mod to be able to read it. If you want to use your own images, you would put them in `inputData`.

**Comment by Atou-Mahogany** [comment]
How do I copy the char_test folder? I am not seeing any option to download it, and right clicking it to Save Link As only gives me HTML as an option.

**Comment by PippleCultist** [comment]
Normally you would click on the green `Code` button and choose download zip or clone the repo. I added the zip of just `char_test` to the release if you don't want to do that though.

**Comment by Atou-Mahogany** [comment]
Thank you for the explanation.

Other than the keyboard stuff I previously mentioned, everything seems to be working now. Although I must note that the Awaken Icon for the weapon is not centered in the game.

Hm, I was honestly expecting a kind of massive library of everything in the game that Players would be picking out of a drop down list in order to piece together the characters they wanted, but this... is not going to be as modular as that like I originally expected. Darn.

In the future, may you consider making such a library for the mod? Something 
that would allow players to specifically choose another character's Weapon/Skill/Special from a drop down list that the game can reference for how it is supposed to function, and then allow Players to customize it afterwords with specific text/modifiers/sprites etc.

For example, a character I would like to make in the future is Aqua but using Ayame's Weapon. So if I could just choose Aqua as a "preset character" and then start swapping out her things for Ayame's things, that would be an ideal starting position to be in. From there just the art resources become the main concern... But actually, if you had it to where exporting the created character automatically generated their PNG assets, then it becomes a simple issue of art swapping for the user.

Sorry, I'm rambling now. Thank you for helping me getting things functioning on my end. I eagerly look foreword to seeing how this mod develops in the future.

**Comment by PippleCultist** [comment]
I'll think about it. It probably won't be any time soon though if I decide to do it.
